### ISSUE TITLE
Heads-up: `python.pythonPath` support will likely be removed

### ISSUE THREAD

**Issue by Sordie** [Whinarn/vscode-python-auto-venv#11]
**Problem**
Right now, this extension relies on setting the path to the environments python executable by changing the settings.json file. As mentioned in [microsoft/vscode-python#12313](https://github.com/microsoft/vscode-python/issues/12313) this option will be removed.

**Possible Solution**
I think the intention is to expose similar functionality via an api, but I'm unsure if it will fit this extension.

**Comment by Whinarn** [comment]
Thank you for the heads up, @Sordie !
I was actually not aware of this.
I'll make sure to check their progress and see what they are planning to replace it with.

**Comment by alexander-minchin** [comment]
Is there any update on this?
Looks like it's now expecting pythonInterpreterPath to be set instead of pythonPath.
My workaround for the moment is manually changing this in the settings.json

**Comment by Whinarn** [comment]
Honestly, I unfortunately don't think there's a future for this extension due to these changes in the vscode-python extension that this extension depends on. And I'm not motivated enough to reach out to them about it since I'm only using this for work, where I will only remain for 3 more weeks. Python is not a personal preference of mine. So I'll likely archive this project soon. But anyone interested is free to pick it up after me.

**Comment by Whinarn** [comment]
Closing this issue since this project is being archived. Thank you for using it and reporting this issue, and sorry for not being able to continue supporting it.
